### ISSUE TITLE
Valeur des états

### ISSUE THREAD

**Issue by BenoitMC** [agilidee/flyboy#12]
Pourquoi avoir des codes du type 0, 1, 2 au lieu de simplement stocker "opened" ou "closed" comme string ?

**Comment by bgantaume** [comment]
très bonne question!
l'option string est mieux!

On Wed, Apr 1, 2015 at 4:44 PM, Benoit MARTIN-CHAVE <
notifications@github.com> wrote:

> Pourquoi avoir des codes du type 0, 1, 2 au lieu de simplement stocker
> "opened" ou "closed" comme string ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agilidee/flyboy/issues/12>.
>



-- 
Benoit @gantaume <http://twitter.com/gantaume>
Catalyseur d'agilité
+33.6.76.31.22.91
http://www.agilidee.com
