### ISSUE TITLE
Boutons d'actions

### ISSUE THREAD

**Issue by BenoitMC** [agilidee/flyboy#19]
Dans Résosign j'ai commencé à changer un peu le positionnement des actions dans les contextes (en bas) et utiliser des icônes à la place des boutons à la place de la liste déroulante du haut : 

J'aime beaucoup le résultat et je pense que ce serait sympa de généraliser.

La bonne nouvelle c'est que comme j'avais fait des helpers, on doit pouvoir changer ça automatiquement dans tous les engines juste en changeant les CSS et les helpers dans Dorsale.

cc @bgantaume 

![capturfiles-20150493_170468](https://cloud.githubusercontent.com/assets/445785/6984459/66338f24-da29-11e4-9d52-36ddcc8ad6ed.png)

**Comment by bgantaume** [comment]
J'aime bien aussi. J'ai peur que cela devienne confusant si l'on a des boutons d'un côté et des icones de l'autre. Comment harmoniser cela?

**Comment by BenoitMC** [comment]
Je passe les boutons en btn-xs + icône en dessous du picto de l'objet
