### ISSUE TITLE
Pagination ?

### ISSUE THREAD

**Issue by BenoitMC** [agilidee/flyboy#46]
Il n'y en avait pas dans l'appli d'origine. C'est normal ?

cc @bgantaume

**Comment by bgantaume** [comment]
que proposes-tu?

2015-04-15 11:03 GMT+02:00 Benoit MARTIN-CHAVE <notifications@github.com>:

> Il n'y en avait pas dans l'appli d'origine. C'est normal ?
>
> cc @bgantaume <https://github.com/bgantaume>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agilidee/flyboy/issues/46>.
>



-- 
Benoit @gantaume <http://twitter.com/gantaume>
Catalyseur d'agilité
+33.6.76.31.22.91
http://www.agilidee.com

**Comment by BenoitMC** [comment]
Pagination à 50 par page

**Comment by BenoitMC** [comment]
Il faut répercuter dans Pilote

**Comment by BenoitMC** [comment]
Ticket ouvert dans Pilote : agilidee/pilote#143
